name: Deploy Databricks Bundle

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Check repository structure
        run: |
          pwd
          ls -la
          echo "Checking asset bundle..."
          ls -la asset_bundle_test_proj
          echo "Checking databricks.yml..."
          ls -la asset_bundle_test_proj/databricks.yml

      - name: Validate Databricks Bundle
        working-directory: ./asset_bundle_test_proj
        run: |
          databricks bundle validate --strict -t prod

      - name: Deploy Databricks Bundle
        working-directory: ./asset_bundle_test_proj
        run: |
          databricks bundle deploy -t prod
